# Autogenerated wrapper script for libmoocore_jll for riscv64-linux-gnu
export libmoocore

JLLWrappers.@generate_wrapper_header("libmoocore")
JLLWrappers.@declare_library_product(libmoocore, "libmoocore.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmoocore,
        "lib/libmoocore.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
