# Autogenerated wrapper script for libmoocore_jll for x86_64-w64-mingw32
export libmoocore

JLLWrappers.@generate_wrapper_header("libmoocore")
JLLWrappers.@declare_library_product(libmoocore, "libmoocore.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmoocore,
        "bin\\libmoocore.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
